name: create a task
description: map out the steps for a feature, bug etc for our hackathon Project
title: <short description of the task>
assignees:
  - nil
body:
  - type: textarea
    id: task-summary
    attributes:
      label: Task Summary
      description: A couple sentences describing what the task should do.
      placeholder: ex 'Add a file to the repository'
    validations:
      required: false
      
  - type: dropdown
    id: scope
    attributes:
      label: Scope
      description: what is the scope of this issue?
      multiple: true
      options:
        - Backend
        - Frontend
        - Database
    validations:
      required: true

  - type: textarea
    id: task-steps
    attributes:
      label: Task Steps
      description: Steps to complete the task in task list format, please copy the line with checkbox if you need more.
      value: '- [ ] create a file named test.md' 
    validations:
      required: true

  - type: textarea
    id: additional-comments
    attributes:
      label: Additional Comments
      description: provide additonal comments or context for the task steps.
      placeholder: - you can the use `touch` command to create the file.
    validations:
      required: true

        